<?php

return array(
    'Bon cadeau pour produit %ref, commande %order' => 'Gift Voucher from product produit %ref, order %order',
    'Ce code promo a été généré automatiquement par le module Bon Cadeau, suite à l\'achat du produit %title (référence %ref), commande %order' => 'This discount code was automatically generated by the Gift Voucher module, from product %title (reference %ref), order %order',
    'This product is a gift voucher' => 'This product is a gift voucher',
);
