<?php

return array(
    'Amount' => 'Amount',
    'Change this coupon' => 'Change this coupon',
    'Coupon code' => 'Coupon code',
    'Days before expiration' => 'Days before expiration',
    'Expiration date' => 'Expiration date',
    'Expired' => 'Expired',
    'Gift Voucher' => 'Gift Voucher',
    'Gift vouchers generated by this order' => 'Gift vouchers generated by this order',
    'Re-send mail' => 'Re-send mail',
    'Send again gift voucher mail to customer' => 'Send again gift voucher mail to customer',
);
