<?php

return array(
    'Amount' => 'Montant',
    'Change this coupon' => 'Modifier ce code promo',
    'Coupon code' => 'Code promo',
    'Days before expiration' => 'Jours avant expiration',
    'Expiration date' => 'Date d\'expiration',
    'Expired' => 'Expiré',
    'Gift Voucher' => 'Bon cadeau',
    'Gift vouchers generated by this order' => 'Bons cadeaux générés par cette commande',
    'Re-send mail' => 'Renvoyer le mail',
    'Send again gift voucher mail to customer' => 'Envoyer à nouveau le mail "bon cadeau" au client',
);
